version: "3"

services:
  rstudio:
    image: "anthesevenants/elastictoolsrtutorial:rstudio"
    ports: 
      - "8787:8787"
      - "8788:8788"
    environment:
      PASSWORD: 'hello'
    volumes:
      - .:/home/rstudio/ElasticToolsR-tutorial/